lib/bibworkflow_admin_blueprint.py
# -*- coding: utf-8 -*-
## This file is part of Invenio.
## Copyright (C) 2012, 2013 CERN.
##
## Invenio is free software; you can redistribute it and/or
## modify it under the terms of the GNU General Public License as
## published by the Free Software Foundation; either version 2 of the
## License, or (at your option) any later version.
##
## Invenio is distributed in the hope that it will be useful, but
## WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
## General Public License for more details.
##
## You should have received a copy of the GNU General Public License
## along with Invenio; if not, write to the Free Software Foundation, Inc.,
## 59 Temple Place, Suite 330, Boston, MA 02111-1307, USA.
"""Holding Pen & BibWorkflow web interface"""

__revision__ = "$Id$"

__lastupdated__ = """$Date$"""

from flask import render_template
from invenio.bibworkflow_model import Workflow, BibWorkflowObject
from invenio.bibworkflow_api import start_delayed
from invenio.bibworkflow_load_workflows import loaded_workflows, workflows
from invenio.webinterface_handler_flask_utils import _, InvenioBlueprint
from invenio.bibworkflow_utils import (get_workflow_definition,
                                       get_redis_keys as utils_get_redis_keys,
                                       filter_holdingpen_results)

import traceback

blueprint = InvenioBlueprint('bibworkflow', __name__,
                             url_prefix="/admin/bibworkflow",
                             menubuilder=[('main.admin.bibworkflow',
                                           _('Configure BibWorkflow'),
                                          'bibworkflow.index')],
                             breadcrumbs=[(_('Administration'),
                                           'help.admin'),
                                          (_('Configure BibWorkflow'),
                                           'bibworkflow.index')],)


@blueprint.route('/', methods=['GET', 'POST'])
@blueprint.route('/index', methods=['GET', 'POST'])
@blueprint.invenio_authenticated
@blueprint.invenio_templated('bibworkflow_index.html')
def index():
    """
    Dispalys main interface of BibWorkflow.
    """
    w = Workflow.query.all()
    filter_keys = utils_get_redis_keys()
    return dict(workflows=w, filter_keys=filter_keys)


@blueprint.route('/entry_details', methods=['GET', 'POST'])
@blueprint.invenio_authenticated
@blueprint.invenio_wash_urlargd({'id_entry': (int, 0)})
def entry_details(id_entry):
    """
    Displays entry details.
    """
    wfe_object = BibWorkflowObject.query.filter(BibWorkflowObject.id == id_entry).first()

    return render_template('bibworkflow_entry_details.html',
                           entry=wfe_object, log="",
                           data_preview=_entry_data_preview(wfe_object.data, 'hd'),
                           workflow_func=get_workflow_definition(wfe_object.bwlWORKFLOW.name))


@blueprint.route('/workflow_details', methods=['GET', 'POST'])
@blueprint.invenio_authenticated
@blueprint.invenio_wash_urlargd({'id_workflow': (unicode, "")})
def workflow_details(id_workflow):
    w_metadata = Workflow.query.filter(Workflow.uuid == id_workflow).first()

    return render_template('bibworkflow_workflow_details.html',
                           workflow_metadata=w_metadata,
                           log="",
                           workflow_func=get_workflow_definition(w_metadata.name))


@blueprint.route('/workflows', methods=['GET', 'POST'])
@blueprint.invenio_authenticated
@blueprint.invenio_templated('bibworkflow_workflows.html')
def show_workflows():
    return dict(workflows=workflows,
                broken_workflows=loaded_workflows.get_broken_plugins())


@blueprint.route('/run_workflow', methods=['GET', 'POST'])
@blueprint.invenio_authenticated
@blueprint.invenio_wash_urlargd({'workflow_name': (unicode, "")})
def run_workflow(workflow_name, data={"data": 10}):
    try:
        print "Starting workflow '%s'" % (workflow_name,)
        start_delayed(workflow_name, data)
    except:
        traceback.print_exc()
    return "Workflow has been started."


@blueprint.route('/entry_data_preview', methods=['GET', 'POST'])
@blueprint.invenio_authenticated
@blueprint.invenio_wash_urlargd({'oid': (int, 0),
                                'of': (unicode, 'default')})
def entry_data_preview(oid, of):
    workflow_object = BibWorkflowObject.query.filter(BibWorkflowObject.id ==
                                                     oid).first()
    return _entry_data_preview(workflow_object.data, of)


@blueprint.route('/get_redis_keys', methods=['GET', 'POST'])
@blueprint.invenio_authenticated
@blueprint.invenio_wash_urlargd({'key': (unicode, "")})
def get_redis_keys(key):
    keys = utils_get_redis_keys(str(key))
    options = ""
    for key in keys:
        options += "<option>%s</option>" % (key,)
    return options


@blueprint.route('/get_redis_values', methods=['GET', 'POST'])
@blueprint.invenio_authenticated
@blueprint.invenio_wash_urlargd({'key': (unicode, "")})
def get_redis_values(key):
    keys = key.split()
    print keys
    values = filter_holdingpen_results(*keys)
    return str(values)


def _entry_data_preview(data, of='default'):
    if format == 'hd' or format == 'xm':
        from invenio.bibformat import format_record
        try:
            data['record'] = format_record(recID=None, of=of,
                                           xml_record=data['record'])
        except:
            print "This is not a XML string"
    try:
        return data['record']
    except:
        return data

lib/bibworkflow_hp_blueprint.py
# -*- coding: utf-8 -*-
## This file is part of Invenio.
## Copyright (C) 2013 CERN.
##
## Invenio is free software; you can redistribute it and/or
## modify it under the terms of the GNU General Public License as
## published by the Free Software Foundation; either version 2 of the
## License, or (at your option) any later version.
##
## Invenio is distributed in the hope that it will be useful, but
## WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
## General Public License for more details.
##
## You should have received a copy of the GNU General Public License
## along with Invenio; if not, write to the Free Software Foundation, Inc.,
## 59 Temple Place, Suite 330, Boston, MA 02111-1307, USA.
"""Holding Pen web interface"""

__revision__ = "$Id$"

__lastupdated__ = """$Date$"""

from flask import render_template
from invenio.bibworkflow_model import BibWorkflowObject, Workflow
from invenio.config import CFG_LOGDIR
from invenio.webinterface_handler_flask_utils import _, InvenioBlueprint
from invenio.bibworkflow_utils import get_workflow_definition
from invenio.bibworkflow_api import continue_oid_delayed
from invenio.bibworkflow_hp_load_widgets import widgets
from invenio.bibworkflow_config import CFG_OBJECT_VERSION

from flask import redirect, url_for, flash
from invenio.bibformat_engine import format_record

from invenio.bibworkflow_utils import create_hp_containers
# from invenio.bibworkflow_containers import bwolist

blueprint = InvenioBlueprint('holdingpen', __name__,
                             url_prefix="/admin/holdingpen",
                             menubuilder=[('main.admin.holdingpen',
                                          _('Holdingpen'),
                                           'holdingpen.index')],
                             breadcrumbs=[(_('Administration'), 'help.admin'),
                                          (_('Holdingpen'),
                                           'holdingpen.index')])


@blueprint.route('/index', methods=['GET', 'POST'])
@blueprint.invenio_authenticated
@blueprint.invenio_templated('bibworkflow_hp_index.html')
def index():
    """
    Displays main interface of BibHoldingpen.
    """
    bwolist = create_hp_containers()
    return dict(hpcontainers=bwolist)


@blueprint.route('/refresh', methods=['GET', 'POST'])
@blueprint.invenio_authenticated
def refresh():
    import invenio.bibworkflow_containers
    reload(invenio.bibworkflow_containers)
    return 'Records Refreshed'


@blueprint.route('/load_table', methods=['GET', 'POST'])
@blueprint.invenio_authenticated
@blueprint.invenio_templated('bibworkflow_hp_index.html')
def load_table():
    """
    Function used for the passing of JSON data to the DataTable
    """
    from flask import request

    from invenio.bibworkflow_containers import bwolist

    iDisplayStart = request.args.get('iDisplayStart')
    iDisplayLength = request.args.get('iDisplayLength')
    # sSearch will be used for searching later
    # sSearch = request.args.get('sSearch')
    # iSortCol_0 = request.args.get('iSortCol_0')
    # sSortDir_0 = request.args.get('sSortDir_0')

    iDisplayStart = int(request.args.get('iDisplayStart'))
    iDisplayLength = int(request.args.get('iDisplayLength'))

    table_data = {
        "aaData": []
    }

    for bwo in bwolist[iDisplayStart:iDisplayStart+iDisplayLength]:
        table_data['sEcho'] = int(request.args.get('sEcho')) + 1
        table_data['iTotalRecords'] = len(bwolist)
        table_data['iTotalDisplayRecords'] = len(bwolist)

        if bwo.version == CFG_OBJECT_VERSION.FINAL:
            bwo_version = \
                '<span class="label label-success">Final</span>'
        elif bwo.version == CFG_OBJECT_VERSION.HALTED:
            bwo_version = \
                '<span class="label label-warning">Halted</span>'
        else:
            bwo_version = \
                '<span class="label label-success">Running</span>'
        if bwo.extra_data['widget'] is not None:
            widget_link = '<a class="btn btn-info"' + \
                          'href="/admin/holdingpen/widget?widget=' + \
                          bwo.extra_data['widget'] + \
                          '&bwobject_id=' + \
                          str(bwo.id) + \
                          '"><i class="icon-wrench"></i></a>'
        else:
            widget_link = None
        table_data['aaData'].append(
            [str(bwo.id),
             None,
             None,
             None,
             str(bwo.id_workflow),
             str(bwo.extra_data['owner']),
             str(bwo.created),
             bwo_version,
             '<a id="info_button" ' +
             'class="btn btn-info pull-center text-center"' +
             'href="/admin/holdingpen/details?bwobject_id=' +
             str(bwo.id) +
             '"><i class="icon-white icon-zoom-in"></i></a>',
             widget_link,
             ])
    return table_data


@blueprint.route('/resolve_approval', methods=['GET', 'POST'])
@blueprint.invenio_wash_urlargd({'bwobject_id': (int, 0)})
def resolve_approval(bwobject_id):
    """
    Resolves the action taken in the approval widget
    """
    from flask import request
    if request.form['submitButton'] == 'Accept':
        continue_oid_delayed(bwobject_id)
        flash('Record Accepted')
    elif request.form['submitButton'] == 'Reject':
        _delete_from_db(bwobject_id)
        flash('Record Rejected')
    return redirect(url_for('holdingpen.index'))


@blueprint.route('/details', methods=['GET', 'POST'])
@blueprint.invenio_authenticated
@blueprint.invenio_wash_urlargd({'bwobject_id': (int, 0)})
def details(bwobject_id):
    """
    Displays info about the hpcontainer, and presents the data
    of all available versions of the object. (Initial, Error, Final)
    """
    # search for parents
    bwobject = BibWorkflowObject.query.filter(BibWorkflowObject.id ==
                                              bwobject_id).first()

    bwparent = BibWorkflowObject.query.filter(BibWorkflowObject.id ==
                                              bwobject.id_parent).first()

    info = get_info(bwobject)
    try:
        info['widget'] = bwobject.extra_data['widget']
    except (KeyError, AttributeError):
        pass

    w_metadata = Workflow.query.filter(Workflow.uuid ==
                                       bwobject.id_workflow).first()
    # read the logtext from the file system
    try:
        f = open(CFG_LOGDIR + "/object_" + str(bwobject.id)
                 + "_w_" + str(bwobject.id_workflow) + ".log", "r")
        logtext = f.read()
    except IOError:
        logtext = ""

    print bwobject.get_data()
    print _entry_data_preview(bwobject.get_data())

    return render_template('bibworkflow_hp_details.html',
                           bwobject=bwobject,
                           bwparent=bwparent,
                           info=info, log=logtext,
                           data_preview=_entry_data_preview(
                               bwobject.get_data()),
                           workflow_func=get_workflow_definition(
                               w_metadata.name).workflow)


@blueprint.route('/restart_record', methods=['GET', 'POST'])
@blueprint.invenio_authenticated
@blueprint.invenio_wash_urlargd({'bwobject_id': (int, 0)})
def restart_record(bwobject_id, start_point='continue_next'):
    """
    Restarts the initial object in its workflow
    """
    continue_oid_delayed(oid=bwobject_id, start_point=start_point)
    return 'Record Restarted'


@blueprint.route('/restart_record_prev', methods=['GET', 'POST'])
@blueprint.invenio_authenticated
@blueprint.invenio_wash_urlargd({'bwobject_id': (int, 0)})
def restart_record_prev(bwobject_id):
    """
    Restarts the initial object in its workflow from the current task
    """
    continue_oid_delayed(oid=bwobject_id, start_point="restart_task")
    print "Record restarted from previous task"


@blueprint.route('/delete_from_db', methods=['GET', 'POST'])
@blueprint.invenio_authenticated
@blueprint.invenio_wash_urlargd({'bwobject_id': (int, 0)})
def delete_from_db(bwobject_id):
    """
    Deletes all available versions of the object from the db
    """
    import invenio.bibworkflow_containers
    _delete_from_db(bwobject_id)
    reload(invenio.bibworkflow_containers)
    flash('Record Deleted')
    return redirect(url_for('holdingpen.index'))


def _delete_from_db(bwobject_id):
    from invenio.sqlalchemyutils import db

    # delete every BibWorkflowObject version from the db
    BibWorkflowObject.query.filter(BibWorkflowObject.id ==
                                   bwobject_id).delete()
    db.session.commit()


@blueprint.route('/widget', methods=['GET', 'POST'])
@blueprint.invenio_authenticated
@blueprint.invenio_wash_urlargd({'bwobject_id': (int, 0),
                                 'widget': (unicode, ' ')})
def show_widget(bwobject_id, widget):
    """
    Renders the bibmatch widget for a specific record
    """
    bwobject = BibWorkflowObject.query.filter(BibWorkflowObject.id ==
                                              bwobject_id).first()
    bwparent = BibWorkflowObject.query.filter(BibWorkflowObject.id ==
                                              bwobject.id_parent).first()

    widget_form = widgets[widget]

    if widget == 'bibmatch_widget':
        # setting up bibmatch widget
        try:
            matches = bwobject.extra_data['tasks_results']['match_record']
        except:
            pass

        match_preview = []
        # adding dummy matches
        match_preview.append(BibWorkflowObject.query.filter(
            BibWorkflowObject.id == bwobject_id).first())
        match_preview.append(BibWorkflowObject.query.filter(
            BibWorkflowObject.id == bwobject_id).first())

        data_preview = _entry_data_preview(bwobject.get_data())

        return render_template('bibworkflow_hp_'+widget+'.html',

templates/workflows/hp_details_base.html
{#
## This file is part of Invenio.
## Copyright (C) 2012, 2013, 2014 CERN.
##
## Invenio is free software; you can redistribute it and/or
## modify it under the terms of the GNU General Public License as
## published by the Free Software Foundation; either version 2 of the
## License, or (at your option) any later version.
##
## Invenio is distributed in the hope that it will be useful, but
## WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
## General Public License for more details.
##
## You should have received a copy of the GNU General Public License
## along with Invenio; if not, write to the Free Software Foundation, Inc.,
## 59 Temple Place, Suite 330, Boston, MA 02111-1307, USA.
#}

{% extends "workflows/hp_base.html" %}
{% import 'workflows/utils.html' as utils %}

{% block header%}
  {{ super() }}
  {% bundles "workflows.js", "workflows.css", "jquery.js" %}
{% endblock header %}

{% block javascript %}
  {{ super() }}

  <script type="text/javascript">
    require(["jquery",
             "js/workflows/details"],
            function($,
                     initialize) {
      var context = {
        preview_url: "{{ url_for('holdingpen.entry_data_preview')|safe }}",
        action_url: "{{ url_for('holdingpen.resolve_action')|safe }}",
        id_object: "{{ bwobject.id }}"
      }
      initialize(context);
    });
  </script>
{%- endblock javascript %}

{% block hpbody %}

  {% block hp_navbar %}
    <nav class="navbar navbar-default" role="navigation">
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      {% block top_left %}
        <ul class="nav navbar-nav">
          <li><a href="{{url_for('holdingpen.maintable')}}" class="navbar-btn-sm"><span class="glyphicon glyphicon-hand-left"></span> {{ _('Back') }}</a>
          </li>
        </ul>
      {% endblock %}
      {% block top_right %}
        <div class="navbar-form navbar-right">
          <a href="{{ url_for('holdingpen.details', objectid=previous_object)}}"
             class="btn btn-default"
             {% if previous_object == None %}disabled="disabled"{% endif %}>
              <span class="glyphicon glyphicon-circle-arrow-left"></span>
              <strong>{{ _('Previous') }}</strong>
          </a>

          <a href="{{ url_for('holdingpen.details', objectid=next_object)}}"
             class="btn btn-default"
             {% if next_object == None %}disabled="disabled"{% endif %}>
                <span class="glyphicon glyphicon-circle-arrow-right"></span>
                <strong>{{ _('Next') }}</strong>
          </a>

        </div>
      {% endblock %}
      </div>
    </nav>
  {% endblock %}

  <div class="container" style="padding-left:0px;">
    <div class="row">
      <div class="col-md-3">

        {% block hpbody_details %}

          {% if "side" in rendered_actions %}
            {{ rendered_actions["side"]|safe }}
          {% endif %}

          <div class="panel panel-info">
            <div class="panel-heading">
              <h3 class="panel-title">{{ _('Workflow status') }}</h3>
            </div>
            <div class="panel-body">
              <p data-toggle="tooltip" data-placement="top" title="{{ workflow.name }}">{{ workflow.name|truncate(25, True) }}</p>
              {% if task_history %}
              <h6 class="pull-left">
                <a role="button" style="cursor: pointer" data-toggle="collapse" data-target="#completed-tasks">
                  {{ _('Completed tasks') }}
                  <span class="caret"></span>
                </a>
              </h6>
              {% endif %}
              <h6 class="pull-right">
                <a role="button" style="cursor: pointer" data-toggle="collapse" data-target="#workflow-definition">
                  {{ _('Definition') }}
                  <span class="caret"></span>
                </a>
              </h6>
              <div class="table table-striped">
                <div class="row"></div>
                {% set id = [] %}
                {% if task_history %}
                  <div id="completed-tasks" class="collapse">
                    <div class="muted"><strong>{{ _('Completed tasks') }}:</strong></div>
                    <div class="list-group">
                      {% for item in task_history %}
                        {{ utils.display_task_history(item.get("nicename"), item.get("doc"), item.get("parameters"), item.get("name"), id|length) }}
                        {% do id.append(1) %}
                      {% endfor %}
                    </div>
                  </div>
                {% endif %}
                <div id="workflow-definition" class="collapse">
                  <div class="muted"><strong>{{ _('Workflow definition') }}:</strong></div>
                  {{ utils.display_workflow_definition(workflow_definition, id) }}
                </div>
              </div>
            </div>
          </div>
          {% if bwobject.get_error_message() %}
          <div class="panel panel-danger">
            <div class="panel-heading">
              <h3 class="panel-title">{{ _('Error occurred') }}</h3>
            </div>
            <div class="panel-body">
              <h5>{{ bwobject.get_extra_data()['_last_task_name'] }}</h5>
              <div class="text-right">
                <h6 id="show-more" class="text-right">
                  <a role="button" data-toggle="modal" style="cursor: pointer" data-target="#error_details_modal" class="float-right">
                    {{ _('Open details') }}</a>
                </h6>
              </div>

              <div class="modal fade" id="error_details_modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                  <div class="modal-content">
                    <div class="modal-header">
                      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                      <h4 class="modal-title" id="myModalLabel">{{ _('Problem with') }}: {{ bwobject.get_extra_data()['_last_task_name'] }}</h4>
                    </div>
                    <div class="modal-body">
                      <p>{{ bwobject.get_error_message()[0] }}</p>
                      <p>{{ bwobject.get_error_message()[1] }}</p>
                    </div>
                    <div class="modal-footer">
                      <button type="button" class="btn btn-default" data-dismiss="modal">{{ _('Close') }}</button>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>

          {% endif %}

          <div class="panel panel-info">
            <div class="panel-heading">
              <h3 class="panel-title">{{ _('Other information') }}</h3>
            </div>
            <div class="panel-body">
              <h6 class="pull-right">
              <a role="button" style="cursor: pointer" data-toggle="collapse" data-target="#record-metadata-table">
                {{ _('More') }}
                <span class="caret"></span>
              </a>
              </h6>
              <div class="row"></div>
              <div id="record-metadata-table" class="collapse">
                <div class="table table-striped">
                    {% for key, value in info.items() %}
                      <b>{{ key }}</b> = {{ value }}
                      <hr>
                    {% endfor %}
                    <span class="label label-{{ bwobject._class}}">{{ bwobject.message }}</span>
                </div>
              </div>
            </div>
          </div>

          {% if history_objects %}
            <div class="panel panel-info">
              <div class="panel-heading">
                <h3 class="panel-title">{{ _('History') }}</h3>
              </div>
              <div class="panel-body">
                <h6 class="pull-right">
                  <a role="button" style="cursor: pointer" data-toggle="collapse" data-target="#History">{{ _('More') }}<span class="caret"></span></a>
                </h6>
                <div class="row"></div>
                <div id="History" class="collapse">
                  <div class="table table-striped">
                    {% for object in history_objects %}
                      {% if  object.id == bwobject.id %}
                        <a href="#">{{ _('current') }} </a> -
                        {% else %}
                        <a href="{{ url_for('holdingpen.details', objectid=object.id) }}" >{{ object.id }}</a> -
                      {% endif %}
                      <span class="label label-{{ object._class }}">{{ object.message }}</span>
                     {{ pretty_date(object.modified) }}
                    <hr>
                    {% endfor %}
                  </div>
                </div>
              </div>
            </div>
          {% endif %}
        {% endblock %}
      </div>
      <div class="col-md-9">
        {% block hp_action_main %}
          {% if "main" in rendered_actions %}
            {{ rendered_actions["main"]|safe }}
          {% endif %}
        {% endblock %}


        {% if 'message' in bwobject.get_extra_data() and bwobject.get_action() != None %}
          <div id="usermessage" class="alert alert-warning alert-dismissible">
            {{ bwobject.get_extra_data()['_message'] }}
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
          </div>
        {% endif %}
        {%- block workflow_completed -%}
          {% if bwobject.version == 1 %}
            <div id="successmessage" class="alert alert-success">
              {{ _('Workflow completed with success') }}
              <a class="close" data-dismiss="alert">×</a>
            </div>
          {% endif %}
        {%- endblock -%}
        {% block hp_preview %}
          {{ _('Display:') }}
          <div id="object-preview"
               class="btn-group btn-group-xs"
               name="object_preview_btn"
               data-toggle="buttons-radio">
            <button class="btn btn-primary preview"
                    type="button"
                    data-id="{{ bwobject.id }}"
                    name="hd">HTML</button>
            <button class="btn btn-primary preview"
                    type="button"
                    data-id="{{ bwobject.id }}"
                    name="xm">MARC</button>
          </div>
          <div id="object_preview_container{{bwobject.id}}" class="object_preview_container">
            {{ data_preview|safe }}
          </div>
        {% endblock %}

        {% block hp_task_results %}
          {% if task_results %}
            {% for template in task_results %}
              {{ template|safe }}
            {% endfor %}
          {% endif %}
        {% endblock %}

        {% block hp_task_logs %}
        <div class="panel panel-warning">
          <div class="panel-heading">
            {{ _("Task logs") }}
          </div>
          <div class="panel-body">
            <div class="list-group">
              {% for entry in bwobject.get_log() %}
                <a href="#" class="list-group-item">{{ entry.created }}: {{ entry.message }}</a>
              {% endfor %}
            </div>
          </div>
        </div>
        {% endblock %}
      </div>
    </div>
  </div>
{% endblock %}

templates/workflows/hp_maintable.html
{#
## This file is part of Invenio.
## Copyright (C) 2014 CERN.
##
## Invenio is free software; you can redistribute it and/or
## modify it under the terms of the GNU General Public License as
## published by the Free Software Foundation; either version 2 of the
## License, or (at your option) any later version.
##
## Invenio is distributed in the hope that it will be useful, but
## WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
## General Public License for more details.
##
## You should have received a copy of the GNU General Public License
## along with Invenio; if not, write to the Free Software Foundation, Inc.,
## 59 Temple Place, Suite 330, Boston, MA 02111-1307, USA.
#}
{% extends "workflows/hp_base.html" %}
{% import 'workflows/utils.html' as utils %}

{% block header %}
  {{ super() }}
  {% bundles "workflows.js", "workflows.css", "jquery.js" %}
{% endblock header %}

{% block javascript %}
  {{ super() }}

  <script type="text/javascript">
    require(["jquery",
             "js/workflows/maintable"],
            function($,
                     initialize) {
      var context = {
        load_table_url: "{{ url_for('holdingpen.load_table')|safe }}",
        tags: JSON.parse('{{tags|safe}}'),
        action_url: "{{ url_for('holdingpen.resolve_action')|safe }}"
      }
      initialize(context);
      $(document).trigger("initHoldingPenTable");
    });
  </script>

{% endblock javascript %}

{% block hpbody %}
  <nav class="navbar navbar-default" role="navigation">
    <div id="bs-example-navbar-collapse-1" class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <p class="navbar-text" style="margin-right:0px; color:light gray;">{{ _('Show Records by') }}:</p>
        <li class="dropdown">
          <a class="dropdown-toggle dropdown-headline" data-toggle="dropdown" href="#">{{ _('Actions') }}<b class="caret"></b></a>
          <ul class="dropdown-menu">
            {% if action_list %}
              {% set i = 0 %}
              {% for task, object_count in action_list.items() %}
                <li><a id="task{{i}}" class="task-btn" tabindex="-1" name="{{task}}">{{ task }}: {{ object_count }}</a></li>
                {% set i = i + 1 %}
              {% endfor %}
            {% else %}
              <li><a class="task-btn">{{ _('No actions') }}</a></li>
            {% endif %}
          </ul>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle dropdown-headline" data-toggle="dropdown">{{ _('Status') }}<b class="caret"></b></a>
          <ul id="tags-menu" class="dropdown-menu" role="menu">
            <li><a id="version-halted" class="version-selection" name="Need action">{{ _('Need action') }}</a></li>
            <li><a id="version-halted" class="version-selection" name="Waiting">{{ _('Waiting') }}</a></li>
            <li><a id="version-completed" class="version-selection" name="Done">{{ _('Done') }}</a></li>
            <li><a id="version-running" class="version-selection" name="In process">{{ _('In process') }}</a></li>
            <li><a id="version-initial" class="version-selection" name="New">{{ _('New') }}</a></li>
            <li><a id="version-error" class="version-selection" name="Error">{{ _('Error') }}</a></li>
          </ul>
        </li>
      </ul>
      <ul id="navbar-right" class="nav navbar-nav navbar-right">
      </ul>
    </div>
  </nav>

  <input class="tags"
         id="tags"
         type="text"
         placeholder="{{ _("Add to search") }}"
         value="" />

  <div class="container">
    <div class="row">
      <table id="maintable"
             cellpadding="0"
             cellspacing="0"
             border="0"
             class="table table-bordered">
        <thead>
          <tr>
            <th></th>
            <th>{{ _('Id') }}</th>
            <th>{{ _('Title') }}</th>
            <th>{{ _('Description') }}</th>
            <th>{{ _('Created') }}</th>
            <th>{{ _('Status') }}</th>
            <th>{{ _('Type') }}</th>
            <th>{{ _('Actions') }}</th>
          </tr>
        </thead>
        <tbody>

        </tbody>
      </table>
    </div>
  </div>
{% endblock %}